server:
  port: ${SERVER_PORT:9080}

spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  security:
    enable-csrf: false
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      host: localhost
      port: 27017
      database: student
      uri: mongodb://localhost:27017/student

  webflux:
    problemdetails:
      enabled: true

  devtools:
    restart:
      enabled: true

  logging:
    level:
      org.springframework.web: INFO
      org.springframework.security: DEBUG
      com.mywhoosh: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  config: classpath:logback-${ENV:development}.xml



