server:
  port: ${SERVER_PORT:9080}

spring:
  main:
    web-application-type: reactive
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      host: localhost
      port: 27017
      database: student
      uri: mongodb://localhost:27017/student

  webflux:
    problemdetails:
      enabled: true

  devtools:
    restart:
      enabled: true

  logging:
    level:
      org.springframework.web: INFO
      org.springframework.security: DEBUG
      com.example: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  config: classpath:logback-${ENV:development}.xml

app:
  public_routes: /login
  jjwt:
    secretKey: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
    expiration: 28800
  password:
    encoder:
      secret: mysecret
      iteration: 33
      keylength: 256

#jwt:
#  password:
#    encoder:
#      secret: oZr417KU7ipPoCCGY0-cPcGu0PpT1_aG9o-BD1KcnN3BpZPrLcNKgcF9QXXJwrY50Whd7Ij51t45oD0ctn-Vo032uFoMtnNzvzpOFq
#      iteration: 33
#      keylength: 256
#  secret: AMDXGbO7gGwf3hoFPpm6GwQvFrqoCsn2 #This Secret For JWT HS256 Signature Algorithm MUST Have 256 bits KeySize
#  expiration: 28800 # token expiration in seconds

